//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public int CurriculumID { get; set; }
        public int SpecialtyID { get; set; }
        public int DisciplineID { get; set; }
        public int Semester { get; set; }
        public int Hours { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
