//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public int StudentID { get; set; }
        public int ScheduleID { get; set; }
        public Nullable<int> GradeValue { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public string Comment { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Student Student { get; set; }
    }
}
