//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryLoan
    {
        public int LoanID { get; set; }
        public int StudentID { get; set; }
        public int ItemID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public System.DateTime DeadlineDate { get; set; }
    
        public virtual LibraryItem LibraryItem { get; set; }
        public virtual Student Student { get; set; }
    }
}
