//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Grade = new HashSet<Grade>();
        }
    
        public int ScheduleID { get; set; }
        public int GroupID { get; set; }
        public int TeacherID { get; set; }
        public int DisciplineID { get; set; }
        public int ClassroomID { get; set; }
        public System.DateTime LessonDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string LessonType { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Discipline Discipline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grade { get; set; }
        public virtual StudyGroup StudyGroup { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
