//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMovementHistory
    {
        public int HistoryID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> OldGroupID { get; set; }
        public Nullable<int> NewGroupID { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Reason { get; set; }
        public string Type { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
